package com.example.tallermobiletpmlapi.entities

import com.example.tptallerdiseniomlapi.entities.Pictures
import com.google.gson.annotations.SerializedName

data class Article(
    @SerializedName("id") val id: String,
    @SerializedName("site_id") val site_id: String,
    @SerializedName("title") val title: String,
    @SerializedName("subtitle") val subtitle: String,
    @SerializedName("seller_id") val seller_id: Int,
    @SerializedName("category_id") val category_id: String,
    @SerializedName("official_store_id") val official_store_id: String,
    @SerializedName("price") val price: String,
    @SerializedName("base_price") val base_price: String,
    @SerializedName("original_price") val original_price: String,
    @SerializedName("currency_id") val currency_id: String,
    @SerializedName("initial_quantity") val initial_quantity: Int,
    @SerializedName("available_quantity") val available_quantity: Int,
    @SerializedName("sold_quantity") val sold_quantity: Int,
//    @SerializedName("sale_terms") val sale_terms : List<Sale_terms>,
    @SerializedName("buying_mode") val buying_mode: String,
    @SerializedName("listing_type_id") val listing_type_id: String,
    @SerializedName("start_time") val start_time: String,
    @SerializedName("stop_time") val stop_time: String,
    @SerializedName("condition") val condition: String,
    @SerializedName("permalink") val permalink: String,
    @SerializedName("thumbnail") val thumbnail: String,
    @SerializedName("secure_thumbnail") val secure_thumbnail: String,
    @SerializedName("pictures") val pictures: ArrayList<Pictures>,
    @SerializedName("video_id") val video_id: String,
    //@SerializedName("descriptions") val descriptions : List<Descriptions>,
    @SerializedName("accepts_mercadopago") val accepts_mercadopago: Boolean,
    // @SerializedName("shipping") val shipping : Shipping,
    @SerializedName("international_delivery_mode") val international_delivery_mode: String,
    // @SerializedName("seller_address") val seller_address : Seller_address,
    @SerializedName("seller_contact") val seller_contact: String,
    //   @SerializedName("location") val location : Location,
    //   @SerializedName("geolocation") val geolocation : Geolocation,
    @SerializedName("coverage_areas") val coverage_areas: List<String>,
    //@SerializedName("attributes") val attributes : List<Attributes>,
    @SerializedName("warnings") val warnings: List<String>,
    @SerializedName("listing_source") val listing_source: String,
    // @SerializedName("variations") val variations : List<String>,
    @SerializedName("status") val status: String,
    @SerializedName("sub_status") val sub_status: List<String>,
    @SerializedName("tags") val tags: List<String>,
    @SerializedName("warranty") val warranty: String,
    @SerializedName("catalog_product_id") val catalog_product_id: String,
    @SerializedName("domain_id") val domain_id: String,
    @SerializedName("parent_item_id") val parent_item_id: String,
    @SerializedName("differential_pricing") val differential_pricing: String,
    @SerializedName("deal_ids") val deal_ids: List<String>,
    @SerializedName("automatic_relist") val automatic_relist: Boolean,
    @SerializedName("date_created") val date_created: String,
    @SerializedName("last_updated") val last_updated: String,
    @SerializedName("health") val health: String,
    @SerializedName("catalog_listing") val catalog_listing: Boolean


    /*  val title: String,
      val thumbnail: String,
      val price: Int,
      val descripcion: String,
      @SerializedName("pictures") val pictures: Array<Pictures>*/
)